# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9962b09397069c795b018bc500e4861e8dc6b2e8bfbbddcb8568d72804b6ee8d3aa27a9b62be463d0db9591601ea4b6322ecd65b5f1504e2c9bce328a030ea2

test:
  secret_key_base: 7f5263e398f321f64b6cc4a3cdb161904ec058d95bb29787bea89b7182d70f4902d65a9655aaaf30b7af219768b453f767b9b948dc7a16fba36ab64bda787a00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
